baseURL: https://bkonetchy.netlify.app
title: Brant Konetchy
theme: hugo-theme-m10c
paginate: 8
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 2
    - identifier: about
      name: About
      url: /about/
      weight: 3
params:
  author: Brant Konetchy
  avatar: "bkavatar2.jpg" 
  description: Data Analyst
  menu_item_separator: ' - '
  social:
    - icon: github
      name: Github
      url: https://github.com/bkonetchy
  style:
    darkestColor: "#6D4C3D"
    darkColor: "#586157"
    lightColor: "#f5e3e0"
    lightestColor: "#f5f5f5"
    primaryColor: "#179FA4"


markup:
  goldmark:
    renderer:
      unsafe: true

