baseURL: https://https://bkonetchy.com
title: Brant Konetchy
theme: hugo-theme-m10c
paginate: 8
menu:
  main:
    - identifier: home
      name: Home
      url: /about/
      weight: 1
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 2
    - identifier: cv
      name: CV
      url: /cv/
      weight: 3
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 4
params:
  author: Brant Konetchy
  avatar: "bkavatar3.jpg" 
  description: Data Analyst
  menu_item_separator: ' - '
  social:
    - icon: github
      name: Github
      url: https://github.com/bkonetchy
    - icon: linkedin
      name: linkedin
      url: https://www.linkedin.com/in/brant-konetchy-56598ba6/
  style:
    darkestColor: "#6D4C3D"
    darkColor: "#586157"
    lightColor: "#E9E0DD"
    lightestColor: "#f5f5f5"
    primaryColor: "#24BBC1"


markup:
  goldmark:
    renderer:
      unsafe: true

