baseURL: https://bkonetchy.netlify.app
title: Introduction
theme: hugo-theme-m10c
paginate: 8
menu:
  main:
    - identifier: about
      name: Home
      url: /about/
      weight: 3
    - identifier: home
      name: Posts
      url: /
      weight: 2
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 3
params:
  author: Brant Konetchy
  avatar: "bkavatar3.jpg" 
  description: Data Analyst
  menu_item_separator: ' - '
  social:
    - icon: github
      name: Github
      url: https://github.com/bkonetchy
  style:
    darkestColor: "#6D4C3D"
    darkColor: "#586157"
    lightColor: "#E9E0DD"
    lightestColor: "#f5f5f5"
    primaryColor: "#24BBC1"


markup:
  goldmark:
    renderer:
      unsafe: true

