---
title: "Magnus Archive Dashboard"
author: "Brant Konetchy"
date: "2020-08-23"
categories: ["R"]
tags: ["R", "leaflet", "ggplot", "database", "Shiny"]
---

# Introduction

Magnus Archives dashboard was developed to allow listeners of the [Magnus Archives Podcast](http://rustyquill.com/the-magnus-archives/), to follow along with the podcast and develop their own research and notes into the cases using an interactive dashboard. The idea was that users could log into a postgres database, add their information to the database, and then view the results in the dashboard. That is still the case for my personal version of the dashboard that I created and use myself, but for this public version I have created a pseudo version in which users can see all the features of the dashboard but not actually connect to a database. The intent is to show off the features of this dashboard and how one could allow users to log in and edit a dashboard. Within the dashboard is a help page that goes into more detail about how to use the dashboard.

You can find the dashboard here: [Magnus Archives Dashboard](https://bkonetchy.shinyapps.io/MagnusArchivePublic/)

You can find the code base here: [Code](https://github.com/bkonetchy/MagnusArchivePublic)

Note: to log into the public version "database" use user name **guest** and password **1234**.
